# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: mat mcloughlin
email: mathew.mcloughlin@gmail.com
description: .Net developer and lover of javascript. I enjoy climbing and surfing (in cold water). I also like to talk about software. Powered by Beard.
baseurl: "" # the subpath of your site, e.g. /blog
url: "mat-mcloughlin.net" # the base hostname & protocol for your site
paginate: 5

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:year/:month/:day/:title/

gems: [jekyll-paginate]
